import { Route, Routes } from "react-router-dom";
import ProductsComponent from "../Products/ProductsComponent";
import products from "../../dt/products.json";
export default function ControllerRoute({ stateBasket, stateModal }) {
  return (
    <div className="cont__allBurgers-wrap">
      <Routes>
        <Route
          path="/"
          element={
            <ProductsComponent
              productArr={products.burgers.items}
              titleProd={products.burgers.title}
              stateBasket={stateBasket}
              stateModal={stateModal}
            />
          }
        />
        <Route
          path="/snaks"
          element={
            <ProductsComponent
              productArr={products.snaks.items}
              titleProd={products.snaks.title}
              stateBasket={stateBasket}
              stateModal={stateModal}
            />
          }
        />
        <Route
          path="/hotDog"
          element={
            <ProductsComponent
              productArr={products.hotDog.items}
              titleProd={products.hotDog.title}
              stateBasket={stateBasket}
              stateModal={stateModal}
            />
          }
        />
        <Route
          path="/combo"
          element={
            <ProductsComponent
              productArr={products.combo.items}
              titleProd={products.combo.title}
              stateBasket={stateBasket}
              stateModal={stateModal}
            />
          }
        />
        <Route
          path="/sawarma"
          element={
            <ProductsComponent
              productArr={products.sawarma.items}
              titleProd={products.sawarma.title}
              stateBasket={stateBasket}
              stateModal={stateModal}
            />
          }
        />
        <Route
          path="/pizza"
          element={
            <ProductsComponent
              productArr={products.pizza.items}
              titleProd={products.pizza.title}
              stateBasket={stateBasket}
              stateModal={stateModal}
            />
          }
        />
        <Route
          path="/wok"
          element={
            <ProductsComponent
              productArr={products.wok.items}
              titleProd={products.wok.title}
              stateBasket={stateBasket}
              stateModal={stateModal}
            />
          }
        />
        <Route
          path="/desserts"
          element={
            <ProductsComponent
              productArr={products.desserts.items}
              titleProd={products.desserts.title}
              stateBasket={stateBasket}
              stateModal={stateModal}
            />
          }
        />
        <Route
          path="/sauces"
          element={
            <ProductsComponent
              productArr={products.sauces.items}
              titleProd={products.sauces.title}
              stateBasket={stateBasket}
              stateModal={stateModal}
            />
          }
        />
      </Routes>
    </div>
  );
}
